2015-09-22 11:03:57,795, Level=ERROR, Pid=4084, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 11:03:57,801, Level=ERROR, Pid=4084, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 11:03:57,805, Level=ERROR, Pid=4084, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 864 : Failed to parse metadata of length 1382: Invalid \escape: line 1 column 186 (char 185)
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 641, in _process_protocol_v2
    metadata, body = self._read_chunk(ifile)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 864, in _read_chunk
    raise RuntimeError('Failed to parse metadata of length {}: {}'.format(metadata_length, error))

2015-09-22 11:05:53,476, Level=ERROR, Pid=1432, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 11:05:53,480, Level=ERROR, Pid=1432, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 11:05:53,483, Level=ERROR, Pid=1432, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 864 : Failed to parse metadata of length 1382: Invalid \escape: line 1 column 186 (char 185)
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 641, in _process_protocol_v2
    metadata, body = self._read_chunk(ifile)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 864, in _read_chunk
    raise RuntimeError('Failed to parse metadata of length {}: {}'.format(metadata_length, error))

2015-09-22 12:01:42,756, Level=ERROR, Pid=1572, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 12:01:42,773, Level=ERROR, Pid=1572, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 12:12:56,658, Level=ERROR, Pid=3172, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 12:12:56,677, Level=ERROR, Pid=3172, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 12:14:47,641, Level=ERROR, Pid=3172, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 864 : Failed to parse metadata of length 1382: Invalid \escape: line 1 column 186 (char 185)
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 641, in _process_protocol_v2
    metadata, body = self._read_chunk(ifile)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 864, in _read_chunk
    raise RuntimeError('Failed to parse metadata of length {}: {}'.format(metadata_length, error))

2015-09-22 12:15:00,737, Level=ERROR, Pid=3768, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 12:15:00,756, Level=ERROR, Pid=3768, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 12:25:57,984, Level=ERROR, Pid=3912, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 12:25:58,003, Level=ERROR, Pid=3912, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 12:28:48,825, Level=ERROR, Pid=2140, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 12:28:48,844, Level=ERROR, Pid=2140, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 12:31:09,920, Level=ERROR, Pid=2848, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 12:31:09,937, Level=ERROR, Pid=2848, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 12:38:24,030, Level=ERROR, Pid=4032, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 12:38:24,049, Level=ERROR, Pid=4032, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 12:40:15,664, Level=ERROR, Pid=2812, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 12:40:15,684, Level=ERROR, Pid=2812, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 12:40:57,846, Level=ERROR, Pid=1540, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 12:40:57,867, Level=ERROR, Pid=1540, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 12:41:09,898, Level=ERROR, Pid=3016, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 12:41:09,914, Level=ERROR, Pid=3016, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 12:43:08,480, Level=ERROR, Pid=3016, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 864 : Failed to parse metadata of length 1388: Invalid \escape: line 1 column 186 (char 185)
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 641, in _process_protocol_v2
    metadata, body = self._read_chunk(ifile)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 864, in _read_chunk
    raise RuntimeError('Failed to parse metadata of length {}: {}'.format(metadata_length, error))

2015-09-22 12:43:37,207, Level=ERROR, Pid=3180, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 12:43:37,224, Level=ERROR, Pid=3180, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 12:44:25,374, Level=ERROR, Pid=3180, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 864 : Failed to parse metadata of length 1388: Invalid \escape: line 1 column 186 (char 185)
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 641, in _process_protocol_v2
    metadata, body = self._read_chunk(ifile)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 864, in _read_chunk
    raise RuntimeError('Failed to parse metadata of length {}: {}'.format(metadata_length, error))

2015-09-22 12:54:11,891, Level=ERROR, Pid=2336, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 12:54:11,908, Level=ERROR, Pid=2336, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 12:54:36,391, Level=ERROR, Pid=2336, File=search_command.py, Line=962, StandardError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43 : test logging_configuration="C:\\Users\\Administrator\\Workspace.private\\splunk-sdks\\splunk-sdk-python\\tests\\searchcommands\\apps\\app_with_logging_configuration\\logging.conf" logging_level="WARNING" record="f" required_option_1="value_1" required_option_2="value_2" show_configuration="f"
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 762, in _process_protocol_v2
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 47, in _execute
    SearchCommand._execute(self, ifile, self.echo)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43, in echo
    raise StandardError(self)

2015-09-22 13:12:04,855, Level=ERROR, Pid=2864, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 13:12:04,871, Level=ERROR, Pid=2864, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 13:12:12,479, Level=ERROR, Pid=2864, File=search_command.py, Line=962, StandardError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43 : test logging_configuration="C:\\Users\\Administrator\\Workspace.private\\splunk-sdks\\splunk-sdk-python\\tests\\searchcommands\\apps\\app_with_logging_configuration\\logging.conf" logging_level="WARNING" record="f" required_option_1="value_1" required_option_2="value_2" show_configuration="f"
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 762, in _process_protocol_v2
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 47, in _execute
    SearchCommand._execute(self, ifile, self.echo)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43, in echo
    raise StandardError(self)

2015-09-22 13:35:31,377, Level=ERROR, Pid=2444, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 13:35:31,392, Level=ERROR, Pid=2444, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 13:35:31,437, Level=ERROR, Pid=2444, File=search_command.py, Line=962, StandardError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43 : test logging_configuration="C:\\Users\\Administrator\\Workspace.private\\splunk-sdks\\splunk-sdk-python\\tests\\searchcommands\\apps\\app_with_logging_configuration\\logging.conf" logging_level="WARNING" record="f" required_option_1="value_1" required_option_2="value_2" show_configuration="f"
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 762, in _process_protocol_v2
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 47, in _execute
    SearchCommand._execute(self, ifile, self.echo)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43, in echo
    raise StandardError(self)

2015-09-22 13:45:13,482, Level=ERROR, Pid=1668, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 13:45:13,499, Level=ERROR, Pid=1668, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 13:45:13,546, Level=ERROR, Pid=1668, File=search_command.py, Line=962, StandardError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43 : test logging_configuration="C:\\Users\\Administrator\\Workspace.private\\splunk-sdks\\splunk-sdk-python\\tests\\searchcommands\\apps\\app_with_logging_configuration\\logging.conf" logging_level="WARNING" record="f" required_option_1="value_1" required_option_2="value_2" show_configuration="f"
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 762, in _process_protocol_v2
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 47, in _execute
    SearchCommand._execute(self, ifile, self.echo)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43, in echo
    raise StandardError(self)

2015-09-22 14:03:22,407, Level=ERROR, Pid=3872, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 14:03:22,413, Level=ERROR, Pid=3872, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 14:03:22,423, Level=ERROR, Pid=3872, File=search_command.py, Line=962, StandardError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43 : test logging_configuration="C:\\Users\\Administrator\\Workspace.private\\splunk-sdks\\splunk-sdk-python\\tests\\searchcommands\\apps\\app_with_logging_configuration\\logging.conf" logging_level="WARNING" record="f" required_option_1="value_1" required_option_2="value_2" show_configuration="f"
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 762, in _process_protocol_v2
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 47, in _execute
    SearchCommand._execute(self, ifile, self.echo)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43, in echo
    raise StandardError(self)

2015-09-22 14:05:40,275, Level=ERROR, Pid=400, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 14:05:40,279, Level=ERROR, Pid=400, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 14:05:40,292, Level=ERROR, Pid=400, File=search_command.py, Line=962, StandardError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43 : test logging_configuration="C:\\Users\\Administrator\\Workspace.private\\splunk-sdks\\splunk-sdk-python\\tests\\searchcommands\\apps\\app_with_logging_configuration\\logging.conf" logging_level="WARNING" record="f" required_option_1="value_1" required_option_2="value_2" show_configuration="f"
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 762, in _process_protocol_v2
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 47, in _execute
    SearchCommand._execute(self, ifile, self.echo)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43, in echo
    raise StandardError(self)

2015-09-22 14:13:14,335, Level=ERROR, Pid=3388, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 14:13:14,339, Level=ERROR, Pid=3388, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 14:13:14,349, Level=ERROR, Pid=3388, File=search_command.py, Line=962, StandardError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43 : test logging_configuration="C:\\Users\\Administrator\\Workspace.private\\splunk-sdks\\splunk-sdk-python\\tests\\searchcommands\\apps\\app_with_logging_configuration\\logging.conf" logging_level="WARNING" record="f" required_option_1="value_1" required_option_2="value_2" show_configuration="f"
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 762, in _process_protocol_v2
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 47, in _execute
    SearchCommand._execute(self, ifile, self.echo)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43, in echo
    raise StandardError(self)

2015-09-22 14:13:45,917, Level=ERROR, Pid=1776, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 14:13:45,921, Level=ERROR, Pid=1776, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 14:13:45,931, Level=ERROR, Pid=1776, File=search_command.py, Line=962, StandardError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43 : test logging_configuration="C:\\Users\\Administrator\\Workspace.private\\splunk-sdks\\splunk-sdk-python\\tests\\searchcommands\\apps\\app_with_logging_configuration\\logging.conf" logging_level="WARNING" record="f" required_option_1="value_1" required_option_2="value_2" show_configuration="f"
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 762, in _process_protocol_v2
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 47, in _execute
    SearchCommand._execute(self, ifile, self.echo)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43, in echo
    raise StandardError(self)

2015-09-22 14:49:02,890, Level=ERROR, Pid=2056, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 14:49:02,895, Level=ERROR, Pid=2056, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 14:49:02,908, Level=ERROR, Pid=2056, File=search_command.py, Line=962, StandardError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43 : test logging_configuration="C:\\Users\\Administrator\\Workspace.private\\splunk-sdks\\splunk-sdk-python\\tests\\searchcommands\\apps\\app_with_logging_configuration\\logging.conf" logging_level="WARNING" record="f" required_option_1="value_1" required_option_2="value_2" show_configuration="f"
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 762, in _process_protocol_v2
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 47, in _execute
    SearchCommand._execute(self, ifile, self.echo)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43, in echo
    raise StandardError(self)

2015-09-22 14:55:48,513, Level=ERROR, Pid=1816, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 14:55:48,517, Level=ERROR, Pid=1816, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 14:55:48,528, Level=ERROR, Pid=1816, File=search_command.py, Line=962, StandardError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43 : test logging_configuration="C:\\Users\\Administrator\\Workspace.private\\splunk-sdks\\splunk-sdk-python\\tests\\searchcommands\\apps\\app_with_logging_configuration\\logging.conf" logging_level="WARNING" record="f" required_option_1="value_1" required_option_2="value_2" show_configuration="f"
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 762, in _process_protocol_v2
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 47, in _execute
    SearchCommand._execute(self, ifile, self.echo)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43, in echo
    raise StandardError(self)

2015-09-22 14:58:38,140, Level=ERROR, Pid=3580, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 14:58:38,144, Level=ERROR, Pid=3580, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 14:58:38,154, Level=ERROR, Pid=3580, File=search_command.py, Line=962, StandardError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43 : test logging_configuration="C:\\Users\\Administrator\\Workspace.private\\splunk-sdks\\splunk-sdk-python\\tests\\searchcommands\\apps\\app_with_logging_configuration\\logging.conf" logging_level="WARNING" record="f" required_option_1="value_1" required_option_2="value_2" show_configuration="f"
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 762, in _process_protocol_v2
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 47, in _execute
    SearchCommand._execute(self, ifile, self.echo)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43, in echo
    raise StandardError(self)

2015-09-22 15:01:32,017, Level=ERROR, Pid=3440, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 15:01:32,023, Level=ERROR, Pid=3440, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 15:01:32,032, Level=ERROR, Pid=3440, File=search_command.py, Line=962, StandardError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43 : test logging_configuration="C:\\Users\\Administrator\\Workspace.private\\splunk-sdks\\splunk-sdk-python\\tests\\searchcommands\\apps\\app_with_logging_configuration\\logging.conf" logging_level="WARNING" record="f" required_option_1="value_1" required_option_2="value_2" show_configuration="f"
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 762, in _process_protocol_v2
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 47, in _execute
    SearchCommand._execute(self, ifile, self.echo)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43, in echo
    raise StandardError(self)

2015-09-22 15:28:23,680, Level=ERROR, Pid=3128, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 15:28:23,684, Level=ERROR, Pid=3128, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 15:28:23,697, Level=ERROR, Pid=3128, File=search_command.py, Line=962, StandardError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43 : test logging_configuration="C:\\Users\\Administrator\\Workspace.private\\splunk-sdks\\splunk-sdk-python\\tests\\searchcommands\\apps\\app_with_logging_configuration\\logging.conf" logging_level="WARNING" record="f" required_option_1="value_1" required_option_2="value_2" show_configuration="f"
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 762, in _process_protocol_v2
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 47, in _execute
    SearchCommand._execute(self, ifile, self.echo)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43, in echo
    raise StandardError(self)

2015-09-22 16:15:46,069, Level=ERROR, Pid=3116, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 16:15:46,075, Level=ERROR, Pid=3116, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 16:15:46,086, Level=ERROR, Pid=3116, File=search_command.py, Line=962, StandardError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43 : test logging_configuration="C:\\Users\\Administrator\\Workspace.private\\splunk-sdks\\splunk-sdk-python\\tests\\searchcommands\\apps\\app_with_logging_configuration\\logging.conf" logging_level="WARNING" record="f" required_option_1="value_1" required_option_2="value_2" show_configuration="f"
Traceback:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 762, in _process_protocol_v2
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 47, in _execute
    SearchCommand._execute(self, ifile, self.echo)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43, in echo
    raise StandardError(self)

2015-09-22 16:25:51,559, Level=ERROR, Pid=2420, File=search_command.py, Line=962, RuntimeError at "../splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "../splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 16:25:51,562, Level=ERROR, Pid=2420, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "../splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "../splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "../splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "../splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 16:25:51,575, Level=ERROR, Pid=2420, File=search_command.py, Line=962, StandardError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43 : test logging_configuration="C:\\Users\\Administrator\\Workspace.private\\splunk-sdks\\splunk-sdk-python\\tests\\searchcommands\\apps\\app_with_logging_configuration\\logging.conf" logging_level="WARNING" record="f" required_option_1="value_1" required_option_2="value_2" show_configuration="f"
Traceback:
  File "../splunklib\searchcommands\search_command.py", line 762, in _process_protocol_v2
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 47, in _execute
    SearchCommand._execute(self, ifile, self.echo)
  File "../splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "../splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43, in echo
    raise StandardError(self)

2015-09-22 17:00:48,651, Level=ERROR, Pid=1248, File=search_command.py, Line=962, RuntimeError at "../splunklib\searchcommands\search_command.py", line 601 : Command test appears to be statically configured for search command protocol version 1 and static configuration is unsupported by splunklib.searchcommands. Please ensure that default/commands.conf contains this stanza:
[test]
filename = test.py
enableheader = true
outputheader = true
requires_srinfo = true
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
Traceback:
  File "../splunklib\searchcommands\search_command.py", line 601, in _process_protocol_v1
    raise RuntimeError(message)

2015-09-22 17:00:48,658, Level=ERROR, Pid=1248, File=search_command.py, Line=962, RuntimeError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87 : Testing
Traceback:
  File "../splunklib\searchcommands\search_command.py", line 586, in _process_protocol_v1
    self._execute(ifile, None)
  File "../splunklib\searchcommands\streaming_command.py", line 54, in _execute
    SearchCommand._execute(self, ifile, self.stream)
  File "../splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "../splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 87, in stream
    raise RuntimeError('Testing')

2015-09-22 17:00:48,674, Level=ERROR, Pid=1248, File=search_command.py, Line=962, StandardError at "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43 : test logging_configuration="C:\\Users\\Administrator\\Workspace.private\\splunk-sdks\\splunk-sdk-python\\tests\\searchcommands\\apps\\app_with_logging_configuration\\logging.conf" logging_level="WARNING" record="f" required_option_1="value_1" required_option_2="value_2" show_configuration="f"
Traceback:
  File "../splunklib\searchcommands\search_command.py", line 762, in _process_protocol_v2
    self._execute(ifile, None)
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 47, in _execute
    SearchCommand._execute(self, ifile, self.echo)
  File "../splunklib\searchcommands\search_command.py", line 830, in _execute
    self._record_writer.write_records(process(self._records(ifile)))
  File "../splunklib\searchcommands\internals.py", line 515, in write_records
    for record in records:
  File "C:\Users\Administrator\Workspace.private\splunk-sdks\splunk-sdk-python\tests\searchcommands\test_search_command.py", line 43, in echo
    raise StandardError(self)

